# [[.ServiceName | title]] Makefile

APP_NAME := [[.ServiceName]]
MAIN     := ./cmd/http/main.go
BUILD    := ./builds/bin/$(APP_NAME)

.PHONY: run build test lint tidy swagger migrate

run:
	go run $(MAIN)

build:
	go build -o $(BUILD) $(MAIN)

test:
	go test ./... -v -cover

lint:
	golangci-lint run ./...

tidy:
	go mod tidy

swagger:
	swag init -g $(MAIN) -o ./docs
[[- if .UseGoose]]

migrate-up:
	goose -dir ./migration/db/postgre postgres "$$DATABASE_URL" up

migrate-down:
	goose -dir ./migration/db/postgre postgres "$$DATABASE_URL" down
[[- else if .UseGolangMigrate]]

migrate-up:
	migrate -path ./migration/db/postgre -database "$$DATABASE_URL" up

migrate-down:
	migrate -path ./migration/db/postgre -database "$$DATABASE_URL" down
[[- end]]

docker-up:
	docker compose up --build -d

docker-down:
	docker compose down

docker-logs:
	docker compose logs -f app
