app:
  name: "GO-COMMUNITY"
  port: ""
  version: ""
  environment: ""
  host: ""
  timeout: 120s
  log_option:
  log_level:
postgresql:
  user: ""
  password: ""
  host: ""
  name: ""
  port:
  ssl_mode: ""
authorization:
  bearer_secret: ""
  bearer_duration: ""
  api_key:
  refresh_secret:
  refresh_expiry:
hash:
  salt: ""